In [56]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [57]:
#Importing the dataset
dataset=pd.read_csv('C:/Users/rukmi/OneDrive/Documents/ML Course/Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values
print(X[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


In [58]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [59]:
#Encoding the categorical data
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:, 2]=le.fit_transform(X[:, 2]) #For Gender column
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [60]:
# For Geography Column-One Hot Encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough') #only 1st column since it has the categorical data
X=np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [61]:
print(X)
print(X[0])

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


In [62]:
#Splitting the dataset into training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [63]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
print(X_train)
print(y_train)

[[-0.99850112  1.71490137 -0.57273139 ... -1.55337352  0.97725852
   0.42739449]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352 -1.02327069
  -1.02548708]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.94479772]
 ...
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.14096853]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
   0.01781218]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017 -1.02327069
  -1.15822478]]
[0 0 1 ... 1 0 1]


In [64]:
#Building the ANN
ann=tf.keras.models.Sequential() #Initialize the neural networks as a sequence of layers.
ann.add(tf.keras.layers.Dense(units=6,activation='relu')) #1st hidden layer.No.of neurons in the hidden layer is 6.
ann.add(tf.keras.layers.Dense(units=6,activation='relu')) #2nd hidden layer.No.of neurons in the hidden layer is 6. 
# Rectifier is the activation function that we use in hidden layers i.e. relu.
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid')) #ouput layer
#Input layer is built automatically depending on the number of features.

In [65]:
#Compilation of ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy']) #loss is binary_crossentropy since the case study is binary classification.
# If it is non-binary classification, the loss would be 'categorical_crossentropy'.
# The optimizer adam processes the ANN via Stochastic Gradient Descent.

In [66]:
#Training the ANN on Training Set.
ann.fit(X_train,y_train,batch_size = 32,epochs=100) #default batch size is 32, where the cost functions till this number is calculated
# and comparison b/w predicted and real values is made.
# We train the ANN in epochs. In every epoch, we can observe the changes in the accuarcy and how the ANN is learning.


Epoch 1/100
250/250 [==============================] - 1s 961us/step - loss: 0.6756 - accuracy: 0.6305
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5026 - accuracy: 0.8014
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4600 - accuracy: 0.8080
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4292 - accuracy: 0.8227
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4040 - accuracy: 0.8338
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3870 - accuracy: 0.8400
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3754 - accuracy: 0.8461
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3681 - accuracy: 0.8501
Epoch 9/100
250/250 [==============================] - 0s 983us/step - loss: 0.3626 - accuracy: 0.8514
Epoch 10/100
250/250 [==============================] - 0s 996us/step - loss: 0.3582 - 

In [67]:
#Prediction
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
#This is the probability of customer leaving the bank.

[[0.02766755]]


In [68]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5) #Getting the result in terms of 0 and 1.
#The customer will not leave the bank i.e. the result is False.

[[False]]


In [73]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


In [75]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1526   59]
 [ 206  209]]


In [76]:
accuracy_score(y_test,y_pred)

0.8675